services:
  php:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8082:443"
    volumes:
      - "./www:/var/www/html"
    networks:
      - internal
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: php-mysql
    ports:
      - "3306:3306"
    volumes:
      - /mysqldata:/var/lib/mysql
    env_file:
      - .env.development
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    networks:
      - internal
    env_file:
      - .env.development
    depends_on:
        - mysql

volumes:
  mysqldata:
    driver: local

networks:
  internal: